### PR TITLE
Vet Clinic Database #1: Create table

### PR DESCRIPTION
**Pull request by miltonHenschel**
- [x] Create tables in SQL.

- [x] Insert and query data in SQL.

- [x] Query results

- https://github.com/miltonHenschel/vet-clinic-db/blob/create-table/screenshots/query1.jpg
- https://github.com/miltonHenschel/vet-clinic-db/blob/create-table/screenshots/query2.jpg
- https://github.com/miltonHenschel/vet-clinic-db/blob/create-table/screenshots/query3.jpg
- https://github.com/miltonHenschel/vet-clinic-db/blob/create-table/screenshots/query4.jpg
- https://github.com/miltonHenschel/vet-clinic-db/blob/create-table/screenshots/query5.jpg
- https://github.com/miltonHenschel/vet-clinic-db/blob/create-table/screenshots/query6.jpg
- https://github.com/miltonHenschel/vet-clinic-db/blob/create-table/screenshots/query7.jpg
- https://github.com/miltonHenschel/vet-clinic-db/blob/create-table/screenshots/query8.jpg

### CODE REVIEW

**Review by Kossi-stack — CHANGES_REQUESTED** [review]
## Hi @miltonHenschel,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 - [ ] Kindly add the screenshot of your query results in the PR description.

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by miltonHenschel** [comment]
Hey @Kossi-stack, thanks for the review but I think I already included the screenshots in the screenshots folder. Pls check it out and lemme know.

**Review by Lameck1 — COMMENTED** [review]
Hello @miltonHenschel👋,

_This is an additional review due to the second opinion request._

I am sorry to report the CR is right. Please stick to this project requirement:

image

Add your screenshots relative to the order of the project requirements in the description of your PR, not in a folder. This means that you have to edit your PR description. After this, please ask for another code review.

NOTE FOR THE NEXT CR: Please ensure that the screenshots that @miltonHenschel is going to add to the PR description are a reflection of the implementation of the project requirements.

Keep rocking 🚀!

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @miltonHenschel 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



 ## Required Changes ♻️

- [ ] I still can't see the screenshot of your query results in the PR description, Please add them as requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by miltonHenschel** [comment]
Sorry @thecodechaser, I requested a second review before the results of the additional review on the first review.

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @miltonHenschel,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

giphy (1)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by mahbubul14 — COMMENTED** [review]
# Project Approved :trophy: :tada: 

Hi @miltonHenschel, 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well-implemented queries.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
